version: "3.8"

volumes:
  n8n_storage:

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - N8N_LICENSE_KEY=b76dae67-9298-413e-b5b3-77fa94e368c1
      - N8N_EDITOR_BASE_URL=https://localhost:8444
      - WEBHOOK_URL=https://localhost:8444/
    volumes:
      - n8n_storage:/home/node/.n8n

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8088:80"   # For HTTP -> HTTPS redirect
      - "8444:443"  # For HTTPS access
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
